"""
Local circuit reference dictionary used by /api/circuits and the frontend
circuit overview pages.

Numbers are reasonable approximations sourced from public Pirelli race
previews + Liberty Media circuit guides.  The frontend treats them as
informational only.
"""

CIRCUITS: list[dict] = [
    {
        "slug": "bahrain",
        "name": "Bahrain International Circuit",
        "country": "Bahrain",
        "city": "Sakhir",
        "lat": 26.0325,
        "lon": 50.5106,
        "length_km": 5.412,
        "turns": 15,
        "drs_zones": 3,
        "lap_record": "1:31.447 — Pedro de la Rosa (2005)",
        "race_distance_km": 308.238,
        "race_laps": 57,
        "safety_car_probability": 0.45,
        "tyre_demand": "High",
        "notes": "Abrasive surface, heavy braking — punishes rear-tyre management.",
    },
    {
        "slug": "jeddah",
        "name": "Jeddah Corniche Circuit",
        "country": "Saudi Arabia",
        "city": "Jeddah",
        "lat": 21.6319,
        "lon": 39.1044,
        "length_km": 6.174,
        "turns": 27,
        "drs_zones": 3,
        "lap_record": "1:30.734 — Lewis Hamilton (2021)",
        "race_distance_km": 308.45,
        "race_laps": 50,
        "safety_car_probability": 0.72,
        "tyre_demand": "Medium",
        "notes": "Fastest street circuit on the calendar. Tight walls — high SC risk.",
    },
    {
        "slug": "albert-park",
        "name": "Albert Park Circuit",
        "country": "Australia",
        "city": "Melbourne",
        "lat": -37.8497,
        "lon": 144.968,
        "length_km": 5.278,
        "turns": 14,
        "drs_zones": 4,
        "lap_record": "1:19.813 — Charles Leclerc (2024)",
        "race_distance_km": 306.124,
        "race_laps": 58,
        "safety_car_probability": 0.55,
        "tyre_demand": "Medium",
        "notes": "Smooth surface, rewards mechanical grip.  Four DRS zones aid overtaking.",
    },
    {
        "slug": "suzuka",
        "name": "Suzuka International Racing Course",
        "country": "Japan",
        "city": "Suzuka",
        "lat": 34.8431,
        "lon": 136.541,
        "length_km": 5.807,
        "turns": 18,
        "drs_zones": 2,
        "lap_record": "1:30.983 — Lewis Hamilton (2019)",
        "race_distance_km": 307.471,
        "race_laps": 53,
        "safety_car_probability": 0.30,
        "tyre_demand": "Very High",
        "notes": "High-energy figure-eight layout — front-left load critical.",
    },
    {
        "slug": "shanghai",
        "name": "Shanghai International Circuit",
        "country": "China",
        "city": "Shanghai",
        "lat": 31.3389,
        "lon": 121.22,
        "length_km": 5.451,
        "turns": 16,
        "drs_zones": 2,
        "lap_record": "1:32.238 — Michael Schumacher (2004)",
        "race_distance_km": 305.066,
        "race_laps": 56,
        "safety_car_probability": 0.40,
        "tyre_demand": "High",
        "notes": "Long back straight enables strong slipstream overtakes.",
    },
    {
        "slug": "miami",
        "name": "Miami International Autodrome",
        "country": "USA",
        "city": "Miami Gardens",
        "lat": 25.9580,
        "lon": -80.2389,
        "length_km": 5.412,
        "turns": 19,
        "drs_zones": 3,
        "lap_record": "1:29.708 — Max Verstappen (2023)",
        "race_distance_km": 308.326,
        "race_laps": 57,
        "safety_car_probability": 0.50,
        "tyre_demand": "Medium",
        "notes": "Surface temperature drives degradation more than air temp.",
    },
    {
        "slug": "imola",
        "name": "Autodromo Enzo e Dino Ferrari",
        "country": "Italy",
        "city": "Imola",
        "lat": 44.3439,
        "lon": 11.7167,
        "length_km": 4.909,
        "turns": 19,
        "drs_zones": 1,
        "lap_record": "1:15.484 — Lewis Hamilton (2020)",
        "race_distance_km": 309.049,
        "race_laps": 63,
        "safety_car_probability": 0.35,
        "tyre_demand": "Medium",
        "notes": "Old-school chicanes, narrow runoffs — track position is everything.",
    },
    {
        "slug": "monaco",
        "name": "Circuit de Monaco",
        "country": "Monaco",
        "city": "Monte Carlo",
        "lat": 43.7347,
        "lon": 7.4206,
        "length_km": 3.337,
        "turns": 19,
        "drs_zones": 1,
        "lap_record": "1:12.909 — Lewis Hamilton (2021)",
        "race_distance_km": 260.286,
        "race_laps": 78,
        "safety_car_probability": 0.78,
        "tyre_demand": "Low",
        "notes": "Slowest layout — qualifying decides 90% of the result.",
    },
    {
        "slug": "spain",
        "name": "Circuit de Barcelona-Catalunya",
        "country": "Spain",
        "city": "Montmeló",
        "lat": 41.5700,
        "lon": 2.2611,
        "length_km": 4.657,
        "turns": 14,
        "drs_zones": 2,
        "lap_record": "1:16.330 — Max Verstappen (2023)",
        "race_distance_km": 308.424,
        "race_laps": 66,
        "safety_car_probability": 0.25,
        "tyre_demand": "Very High",
        "notes": "All-round technical reference — aero, mechanical & tyre demand all high.",
    },
    {
        "slug": "canada",
        "name": "Circuit Gilles Villeneuve",
        "country": "Canada",
        "city": "Montréal",
        "lat": 45.5050,
        "lon": -73.5228,
        "length_km": 4.361,
        "turns": 14,
        "drs_zones": 3,
        "lap_record": "1:13.078 — Valtteri Bottas (2019)",
        "race_distance_km": 305.270,
        "race_laps": 70,
        "safety_car_probability": 0.68,
        "tyre_demand": "Low",
        "notes": "Park circuit with Wall of Champions — SC interventions common.",
    },
    {
        "slug": "silverstone",
        "name": "Silverstone Circuit",
        "country": "UK",
        "city": "Silverstone",
        "lat": 52.0786,
        "lon": -1.0169,
        "length_km": 5.891,
        "turns": 18,
        "drs_zones": 2,
        "lap_record": "1:27.097 — Max Verstappen (2020)",
        "race_distance_km": 306.198,
        "race_laps": 52,
        "safety_car_probability": 0.32,
        "tyre_demand": "Very High",
        "notes": "Maggotts-Becketts-Chapel sequence is the highest-G section of the year.",
    },
    {
        "slug": "hungary",
        "name": "Hungaroring",
        "country": "Hungary",
        "city": "Mogyoród",
        "lat": 47.5789,
        "lon": 19.2486,
        "length_km": 4.381,
        "turns": 14,
        "drs_zones": 1,
        "lap_record": "1:16.627 — Lewis Hamilton (2020)",
        "race_distance_km": 306.630,
        "race_laps": 70,
        "safety_car_probability": 0.30,
        "tyre_demand": "Medium",
        "notes": "Monaco-without-walls. Hot races stress brakes & rear tyres.",
    },
    {
        "slug": "spa",
        "name": "Circuit de Spa-Francorchamps",
        "country": "Belgium",
        "city": "Stavelot",
        "lat": 50.4372,
        "lon": 5.9714,
        "length_km": 7.004,
        "turns": 20,
        "drs_zones": 2,
        "lap_record": "1:46.286 — Valtteri Bottas (2018)",
        "race_distance_km": 308.052,
        "race_laps": 44,
        "safety_car_probability": 0.55,
        "tyre_demand": "Medium",
        "notes": "Mixed weather possible across both ends of the circuit simultaneously.",
    },
    {
        "slug": "zandvoort",
        "name": "Circuit Zandvoort",
        "country": "Netherlands",
        "city": "Zandvoort",
        "lat": 52.3888,
        "lon": 4.5409,
        "length_km": 4.259,
        "turns": 14,
        "drs_zones": 2,
        "lap_record": "1:11.097 — Lewis Hamilton (2021)",
        "race_distance_km": 306.587,
        "race_laps": 72,
        "safety_car_probability": 0.40,
        "tyre_demand": "Medium",
        "notes": "Banked corners at T3 and T14 unlock unique racing lines.",
    },
    {
        "slug": "monza",
        "name": "Autodromo Nazionale Monza",
        "country": "Italy",
        "city": "Monza",
        "lat": 45.6156,
        "lon": 9.2811,
        "length_km": 5.793,
        "turns": 11,
        "drs_zones": 2,
        "lap_record": "1:21.046 — Rubens Barrichello (2004)",
        "race_distance_km": 306.720,
        "race_laps": 53,
        "safety_car_probability": 0.45,
        "tyre_demand": "Medium",
        "notes": "Lowest-downforce setup of the year. Slipstream defines qualifying.",
    },
    {
        "slug": "baku",
        "name": "Baku City Circuit",
        "country": "Azerbaijan",
        "city": "Baku",
        "lat": 40.3725,
        "lon": 49.8533,
        "length_km": 6.003,
        "turns": 20,
        "drs_zones": 2,
        "lap_record": "1:43.009 — Charles Leclerc (2019)",
        "race_distance_km": 306.049,
        "race_laps": 51,
        "safety_car_probability": 0.80,
        "tyre_demand": "Low",
        "notes": "Longest top-speed straight on the calendar. SC almost guaranteed.",
    },
    {
        "slug": "singapore",
        "name": "Marina Bay Street Circuit",
        "country": "Singapore",
        "city": "Singapore",
        "lat": 1.2914,
        "lon": 103.864,
        "length_km": 4.940,
        "turns": 19,
        "drs_zones": 3,
        "lap_record": "1:35.867 — Lewis Hamilton (2023)",
        "race_distance_km": 308.706,
        "race_laps": 62,
        "safety_car_probability": 0.85,
        "tyre_demand": "Medium",
        "notes": "Highest physical demand of the year — humidity destroys drivers.",
    },
    {
        "slug": "austin",
        "name": "Circuit of the Americas",
        "country": "USA",
        "city": "Austin",
        "lat": 30.1328,
        "lon": -97.6411,
        "length_km": 5.513,
        "turns": 20,
        "drs_zones": 2,
        "lap_record": "1:36.169 — Charles Leclerc (2019)",
        "race_distance_km": 308.405,
        "race_laps": 56,
        "safety_car_probability": 0.30,
        "tyre_demand": "High",
        "notes": "Bumpy surface stresses ride height and porpoising margins.",
    },
    {
        "slug": "mexico",
        "name": "Autódromo Hermanos Rodríguez",
        "country": "Mexico",
        "city": "Mexico City",
        "lat": 19.4042,
        "lon": -99.0907,
        "length_km": 4.304,
        "turns": 17,
        "drs_zones": 3,
        "lap_record": "1:17.774 — Valtteri Bottas (2021)",
        "race_distance_km": 305.354,
        "race_laps": 71,
        "safety_car_probability": 0.35,
        "tyre_demand": "Low",
        "notes": "Thin air at altitude — cooling and downforce are the key constraints.",
    },
    {
        "slug": "interlagos",
        "name": "Autódromo José Carlos Pace",
        "country": "Brazil",
        "city": "São Paulo",
        "lat": -23.7036,
        "lon": -46.6997,
        "length_km": 4.309,
        "turns": 15,
        "drs_zones": 2,
        "lap_record": "1:10.540 — Valtteri Bottas (2018)",
        "race_distance_km": 305.879,
        "race_laps": 71,
        "safety_car_probability": 0.45,
        "tyre_demand": "Medium",
        "notes": "Anti-clockwise layout fatigues neck muscles. Rain frequent.",
    },
    {
        "slug": "lasvegas",
        "name": "Las Vegas Strip Circuit",
        "country": "USA",
        "city": "Las Vegas",
        "lat": 36.1175,
        "lon": -115.1736,
        "length_km": 6.201,
        "turns": 17,
        "drs_zones": 2,
        "lap_record": "1:34.876 — Oscar Piastri (2024)",
        "race_distance_km": 309.958,
        "race_laps": 50,
        "safety_car_probability": 0.60,
        "tyre_demand": "Low",
        "notes": "Cold night race — graining the dominant tyre limitation.",
    },
    {
        "slug": "qatar",
        "name": "Lusail International Circuit",
        "country": "Qatar",
        "city": "Lusail",
        "lat": 25.4900,
        "lon": 51.4542,
        "length_km": 5.419,
        "turns": 16,
        "drs_zones": 1,
        "lap_record": "1:24.319 — Lando Norris (2024)",
        "race_distance_km": 308.611,
        "race_laps": 57,
        "safety_car_probability": 0.40,
        "tyre_demand": "Very High",
        "notes": "Sustained high-speed corners — Pirelli mandates max stint length.",
    },
    {
        "slug": "abu-dhabi",
        "name": "Yas Marina Circuit",
        "country": "UAE",
        "city": "Abu Dhabi",
        "lat": 24.4672,
        "lon": 54.6031,
        "length_km": 5.281,
        "turns": 16,
        "drs_zones": 2,
        "lap_record": "1:26.103 — Max Verstappen (2021)",
        "race_distance_km": 306.183,
        "race_laps": 58,
        "safety_car_probability": 0.40,
        "tyre_demand": "Medium",
        "notes": "Dusk-to-night transition shifts grip dramatically mid-race.",
    },
]


def list_circuits() -> list[dict]:
    return CIRCUITS


def get_circuit(slug: str) -> dict | None:
    slug = slug.lower()
    for c in CIRCUITS:
        if c["slug"] == slug:
            return c
    return None
